import type {
  ApiTestSuggestion,
  MaestroFlow,
  RepoScanResult,
  RiskArea,
  SelectorGap,
  TestPlan
} from "../types/TestArchitecture.js";

export class TestArchitectAgent {
  createPlan(feature: string, repoScan: RepoScanResult): TestPlan {
    const risks = this.identifyRisks(feature, repoScan);
    const selectorGaps = this.findSelectorGaps(repoScan);
    const maestroFlow = this.createMaestroFlow(feature, repoScan);
    const apiTest = this.createApiTestSuggestion(feature, repoScan);

    return {
      feature,
      generatedAt: new Date().toISOString(),
      summary: `Deterministic MVP analysis for "${feature}" found ${repoScan.totals.filesScanned} relevant source files, ${repoScan.detections.screens.length} screen names, ${repoScan.detections.routeNames.length} route names, ${repoScan.detections.apiEndpoints.length} API endpoint strings, and prioritized user journey, API contract, selector, and regression risks.`,
      risks,
      selectorGaps,
      maestroFlows: [maestroFlow],
      apiTestSuggestions: [apiTest],
      recommendedNextSteps: [
        "Review high-risk flows with product and QA before automating.",
        "Add stable testID values to primary interaction targets used by Maestro.",
        "Add accessibilityLabel values to interactive controls that are read by screen readers.",
        "Promote generated API test suggestions into the app repo once endpoint paths are confirmed.",
        "Wire a real LLM provider behind TestArchitectAgent after evals are stable."
      ],
      repoScan
    };
  }

  createMaestroFlow(feature: string, repoScan?: RepoScanResult): MaestroFlow {
    const slug = this.slugify(feature);
    const title = this.titleCase(feature);
    const routeNames = repoScan?.detections.routeNames.map((route) => route.value) ?? [];
    const screenNames = repoScan?.detections.screens.map((screen) => screen.value) ?? [];
    const testIds = repoScan?.detections.testIds.map((testId) => testId.value) ?? [];
    const accessibilityLabels = repoScan?.detections.accessibilityLabels.map((label) => label.value) ?? [];
    const inputIds = testIds.filter((value) => /(input|field|search|name|email|password|text|description|title)/i.test(value));
    const actionIds = testIds.filter((value) => /(button|save|submit|continue|next|add|create|login|sign|tap|press)/i.test(value));
    const otherIds = testIds.filter((value) => !inputIds.includes(value) && !actionIds.includes(value));
    const primaryVisibleText = [...accessibilityLabels, ...routeNames, ...screenNames].slice(0, 3);
    const orderedTapTargets = [...actionIds, ...otherIds].slice(0, 4);
    const yamlLines = [
      "appId: REPLACE_WITH_APP_ID",
      "---",
      `# Generated by ai-mobile-test-architect for ${this.yamlQuote(title)}.`,
      "# Replace appId and any sample input values before committing to the target app.",
      "- launchApp"
    ];

    for (const value of primaryVisibleText) {
      yamlLines.push(`- assertVisible: ${this.yamlQuote(value)}`);
    }

    for (const inputId of inputIds.slice(0, 2)) {
      yamlLines.push("- tapOn:", `    id: ${this.yamlQuote(inputId)}`, `- inputText: ${this.yamlQuote(this.sampleInputFor(inputId))}`);
    }

    for (const targetId of orderedTapTargets) {
      yamlLines.push("- tapOn:", `    id: ${this.yamlQuote(targetId)}`);
    }

    if (!primaryVisibleText.length && !testIds.length) {
      yamlLines.push(
        `- assertVisible: ${this.yamlQuote(title)}`,
        "# No literal testID or accessibilityLabel values were detected. Add stable selectors, then replace this assertion with repo-specific steps."
      );
    }

    return {
      name: `${title} generated happy path`,
      fileName: `maestro/${slug}-generated-flow.yaml`,
      yaml: `${yamlLines.join("\n")}\n`
    };
  }

  createApiTestSuggestion(feature: string, repoScan?: RepoScanResult): ApiTestSuggestion {
    const title = this.titleCase(feature);
    const slug = this.slugify(feature);
    const endpoints = repoScan?.detections.apiEndpoints.map((endpoint) => endpoint.value).slice(0, 6) ?? [];
    const endpointList = endpoints.length ? endpoints : ["/api/REPLACE_WITH_ENDPOINT"];

    return {
      name: `${title} API contract suggestion`,
      fileName: `api/${slug}-api-contract.generated.test.ts`,
      notes: [
        "Generated as a fetch-based contract smoke test that can run in Jest or Vitest.",
        endpoints.length
          ? `Seeded from ${endpoints.length} detected endpoint string${endpoints.length === 1 ? "" : "s"}.`
          : "No endpoints were detected, so the generated file includes a placeholder endpoint."
      ],
      code: `const API_BASE_URL = process.env.API_BASE_URL ?? "http://localhost:3000";

const endpoints = ${JSON.stringify(endpointList, null, 2)};

function materializeEndpoint(endpoint: string): string {
  return endpoint
    .replace(/\\$\\{[^}]+\\}/g, "test-id")
    .replace(/:[A-Za-z_][A-Za-z0-9_]*/g, "test-id");
}

function toUrl(endpoint: string): string {
  const materialized = materializeEndpoint(endpoint);

  try {
    return new URL(materialized).toString();
  } catch {
    const normalizedPath = materialized.startsWith("/") ? materialized : \`/\${materialized}\`;
    return new URL(normalizedPath, API_BASE_URL).toString();
  }
}

describe("${title} API contract smoke", () => {
  it.each(endpoints)("responds without a server error for %s", async (endpoint) => {
    const response = await fetch(toUrl(endpoint));

    expect(response.status).toBeLessThan(500);
  });
});
`
    };
  }

  private identifyRisks(feature: string, repoScan: RepoScanResult): RiskArea[] {
    const navigationFiles = repoScan.files.filter((file) => file.signals.includes("navigation"));
    const apiFiles = repoScan.files.filter((file) => file.signals.includes("api-client"));
    const listFiles = repoScan.files.filter((file) => file.signals.includes("list-ui"));
    const routes = this.formatExamples(repoScan.detections.routeNames.map((route) => route.value));
    const screens = this.formatExamples(repoScan.detections.screens.map((screen) => screen.value));
    const endpoints = this.formatExamples(repoScan.detections.apiEndpoints.map((endpoint) => endpoint.value));
    const testIds = this.formatExamples(repoScan.detections.testIds.map((testId) => testId.value));
    const accessibilityLabels = this.formatExamples(
      repoScan.detections.accessibilityLabels.map((accessibilityLabel) => accessibilityLabel.value)
    );

    return [
      {
        id: "journey-happy-path",
        title: `${this.titleCase(feature)} happy path`,
        level: "high",
        why: "The primary workflow must be stable before lower-value edge cases are automated.",
        evidence: [
          `${listFiles.length} list-oriented files suggest the feature depends on rendered collection state.`,
          `${navigationFiles.length} navigation files suggest screen transitions are part of the journey.`,
          routes ? `Detected route names: ${routes}.` : "No literal route names were detected.",
          screens ? `Detected screen components: ${screens}.` : "No screen-like component names were detected."
        ],
        recommendedCoverage: [
          "Maestro flow for launch, create, save, and verify persisted UI state.",
          "A negative-path E2E check for empty required fields.",
          "Smoke coverage on a fresh install with no pre-existing local data."
        ]
      },
      {
        id: "api-contract",
        title: "API contract and validation",
        level: apiFiles.length > 0 ? "high" : "medium",
        why: "Mobile UI failures often come from backend payload shape drift or validation mismatches.",
        evidence: [
          `${apiFiles.length} API-like files found.`,
          endpoints ? `Detected endpoint strings: ${endpoints}.` : "No literal API endpoint strings were detected."
        ],
        recommendedCoverage: [
          "Supertest create/list contract tests.",
          "Validation tests for required fields and malformed payloads.",
          "Error shape assertions that match UI error rendering."
        ]
      },
      {
        id: "selector-accessibility",
        title: "Selector and accessibility readiness",
        level: repoScan.totals.testIds < 5 || repoScan.totals.accessibilityLabels < 5 ? "high" : "medium",
        why: "Stable automation and accessible UI both depend on intentional identifiers and labels.",
        evidence: [
          `${repoScan.totals.testIds} testID selectors found.`,
          `${repoScan.totals.accessibilityLabels} accessibility labels found.`,
          testIds ? `Existing testID values include: ${testIds}.` : "No literal testID values were detected.",
          accessibilityLabels
            ? `Existing accessibilityLabel values include: ${accessibilityLabels}.`
            : "No literal accessibilityLabel values were detected."
        ],
        recommendedCoverage: [
          "Add testID to create, save, input, list, and card elements.",
          "Add accessibilityLabel to touch targets that do not have clear visible text.",
          "Prefer semantic visible text assertions where it is stable."
        ]
      }
    ];
  }

  private findSelectorGaps(repoScan: RepoScanResult): SelectorGap[] {
    return repoScan.files
      .filter(
        (file) =>
          file.signals.includes("interactive-ui") &&
          (file.testIdCount < file.interactiveElementCount || file.accessibilityLabelCount < file.interactiveElementCount)
      )
      .slice(0, 8)
      .map((file) => ({
        file: file.path,
        issue: `Interactive UI detected with ${file.interactiveElementCount} controls, ${file.testIdCount} testID values, and ${file.accessibilityLabelCount} accessibilityLabel values.`,
        recommendation: "Add stable testID values for automation and accessibilityLabel values for non-text controls."
      }));
  }

  private titleCase(value: string): string {
    return value
      .split(/\s+/)
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }

  private slugify(value: string): string {
    return value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "");
  }

  private yamlQuote(value: string): string {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }

  private sampleInputFor(testId: string): string {
    if (/email/i.test(testId)) return "qa@example.com";
    if (/password/i.test(testId)) return "Password123!";
    if (/search/i.test(testId)) return "test";
    if (/description/i.test(testId)) return "Generated QA test description";
    if (/name|title/i.test(testId)) return "Generated QA test";
    return "Generated test value";
  }

  private formatExamples(values: string[], limit = 6): string {
    const uniqueValues = [...new Set(values)];
    const examples = uniqueValues.slice(0, limit).join(", ");
    const remaining = uniqueValues.length - limit;

    if (!examples) return "";
    return remaining > 0 ? `${examples}, and ${remaining} more` : examples;
  }
}
